// 地图预研层共享城市身份；只服务机场/铁路预研，不写入 Airport 主配置。
const TRANSPORT_CITIES = [
  ["beijing", "北京"],
  ["xiongan", "雄安"],
  ["baoding", "保定"],
  ["shijiazhuang", "石家庄"],
  ["xingtai", "邢台"],
  ["handan", "邯郸"],
  ["anyang", "安阳"],
  ["hebi", "鹤壁"],
  ["xinxiang", "新乡"],
  ["zhengzhou", "郑州"],
  ["xuchang", "许昌"],
  ["luohe", "漯河"],
  ["zhumadian", "驻马店"],
  ["xinyang", "信阳"],
  ["xiaogan", "孝感"],
  ["wuhan", "武汉"],
  ["xianning", "咸宁"],
  ["yueyang", "岳阳"],
  ["changsha", "长沙"],
  ["zhuzhou", "株洲"],
  ["hengyang", "衡阳"],
  ["chenzhou", "郴州"],
  ["shaoguan", "韶关"],
  ["qingyuan", "清远"],
  ["guangzhou", "广州"],
  ["hengshui", "衡水"],
  ["liaocheng", "聊城"],
  ["puyang", "濮阳"],
  ["heze", "菏泽"],
  ["shangqiu", "商丘"],
  ["bozhou", "亳州"],
  ["fuyang", "阜阳"],
  ["huainan", "淮南"],
  ["hefei", "合肥"],
  ["wuhu", "芜湖"],
  ["xuancheng", "宣城"],
  ["huzhou", "湖州"],
  ["hangzhou", "杭州"],
  ["luan", "六安"],
  ["jiujiang", "九江"],
  ["nanchang", "南昌"],
  ["jian", "吉安"],
  ["ganzhou", "赣州"],
  ["heyuan", "河源"],
  ["huizhou", "惠州"],
  ["dongguan", "东莞"],
  ["shenzhen", "深圳"],
  ["hongkong", "香港", "hk_macao_taiwan"],
  ["langfang", "廊坊"],
  ["tianjin", "天津"],
  ["cangzhou", "沧州"],
  ["dezhou", "德州"],
  ["jinan", "济南"],
  ["taian", "泰安"],
  ["zaozhuang", "枣庄"],
  ["xuzhou", "徐州"],
  ["suzhou_anhui", "宿州"],
  ["bengbu", "蚌埠"],
  ["chuzhou", "滁州"],
  ["nanjing", "南京"],
  ["zhenjiang", "镇江"],
  ["changzhou", "常州"],
  ["wuxi", "无锡"],
  ["suzhou", "苏州"],
  ["shanghai", "上海"],
  ["jiaxing", "嘉兴"],
  ["jinhua", "金华"],
  ["quzhou", "衢州"],
  ["shangrao", "上饶"],
  ["yingtan", "鹰潭"],
  ["fuzhou_jiangxi", "抚州"],
  ["yichun_jiangxi", "宜春"],
  ["pingxiang", "萍乡"],
  ["xiangtan", "湘潭"],
  ["loudi", "娄底"],
  ["huaihua", "怀化"],
  ["kaili", "凯里"],
  ["guiyang", "贵阳"],
  ["anshun", "安顺"],
  ["qujing", "曲靖"],
  ["kunming", "昆明"],
  ["nantong", "南通"],
  ["taizhou", "泰州"],
  ["yangzhou", "扬州"],
  ["jianghan", "江汉"],
  ["jingmen", "荆门"],
  ["yichang", "宜昌"],
  ["enshi", "恩施"],
  ["fuling", "涪陵"],
  ["chongqing", "重庆"],
  ["chengdu", "成都"],
  ["lianyungang", "连云港"],
  ["kaifeng", "开封"],
  ["luoyang", "洛阳"],
  ["sanmenxia", "三门峡"],
  ["weinan", "渭南"],
  ["xian", "西安"],
  ["xianyang", "咸阳"],
  ["baoji", "宝鸡"],
  ["tianshui", "天水"],
  ["dingxi", "定西"],
  ["lanzhou", "兰州"],
  ["pingdingshan", "平顶山"],
  ["nanyang", "南阳"],
  ["xiangyang", "襄阳"],
  ["shennongjia", "神农架"],
  ["wanzhou", "万州"],
  ["hanzhong", "汉中"],
  ["guangyuan", "广元"],
  ["mianyang", "绵阳"],
  ["deyang", "德阳"],
  ["meishan", "眉山"],
  ["leshan", "乐山"],
  ["yibin", "宜宾"],
  ["bijie", "毕节"],
  ["longnan", "陇南"],
  ["nanchong", "南充"],
  ["guangan", "广安"],
  ["zhangjiakou", "张家口"],
  ["ulanqab", "乌兰察布"],
  ["hohhot", "呼和浩特"],
  ["baotou", "包头"],
  ["datong", "大同"],
  ["shuozhou", "朔州"],
  ["xinzhou", "忻州"],
  ["taiyuan", "太原"],
  ["jinzhong", "晋中"],
  ["linfen", "临汾"],
  ["yuncheng", "运城"],
  ["rizhao", "日照"],
  ["linyi", "临沂"],
  ["jining", "济宁"],
  ["yangquan", "阳泉"],
  ["ziyang", "资阳"],
  ["neijiang", "内江"],
  ["bayannur", "巴彦淖尔"],
  ["ordos", "鄂尔多斯"],
  ["wuhai", "乌海"],
  ["shizuishan", "石嘴山"],
  ["yinchuan", "银川"],
  ["chengde", "承德"],
  ["chaoyang_liaoning", "朝阳"],
  ["fuxin", "阜新"],
  ["shenyang", "沈阳"],
  ["tieling", "铁岭"],
  ["siping", "四平"],
  ["changchun", "长春"],
  ["harbin", "哈尔滨"]
].map(([id, name, region = "china_mainland"]) => ({ id, name, region }));

const CITY_ID_BY_NAME = Object.fromEntries(TRANSPORT_CITIES.map((city) => [city.name, city.id]));

if (typeof AIRPORTS !== "undefined") {
  AIRPORTS.forEach((airport) => {
    const cityId = CITY_ID_BY_NAME[airport.city];
    if (cityId) airport.city_id = cityId;
  });
}

if (typeof RAILWAYS !== "undefined") {
  RAILWAYS.forEach((line) => {
    line.stations.forEach((station) => {
      const cityId = CITY_ID_BY_NAME[station.city];
      if (cityId) station.city_id = cityId;
    });
  });
}
